import './style.css';

const fallback = {
  heroImage: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&w=1800&q=85',
  solarImage: 'https://images.unsplash.com/photo-1497440001374-f26997328c1b?auto=format&fit=crop&w=1000&q=85',
  electricImage: 'https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?auto=format&fit=crop&w=1000&q=85',
  businessName: 'Solara & Volt',
  tagline: 'Energy, made dependable.',
  phone: '+91 98765 43210',
  email: 'hello@solaravolt.in'
};
const content = { ...fallback, ...JSON.parse(localStorage.getItem('sv-content') || '{}') };
const app = document.querySelector('#app');

const icon = (name) => ({arrow:'↗', sun:'☼', bolt:'ϟ', menu:'☰', close:'×', check:'✓'})[name];
function save(){ localStorage.setItem('sv-content', JSON.stringify(content)); }
function nav(){ return `<header class="nav"><a class="brand" href="#home"><span class="mark">S</span><span>${content.businessName}</span></a><button class="mobile-menu" aria-label="Open navigation">${icon('menu')}</button><nav><a href="#solar">Solar</a><a href="#electrical">Electrical</a><a href="#about">About us</a><a href="#contact">Contact</a></nav><a class="nav-cta" href="#contact">Get a consultation <span>${icon('arrow')}</span></a></header>`; }
function home(){return `<main id="home"><section class="hero"><div class="hero-bg" style="background-image:linear-gradient(90deg,rgba(4,29,24,.9) 0%,rgba(4,29,24,.42) 55%,rgba(4,29,24,.15)),url('${content.heroImage}')"></div><div class="hero-sun"><i></i><i></i><i></i><i></i><b></b></div><div class="hero-copy"><p class="eyebrow">Independent energy specialists · since 2011</p><h1>${content.tagline.replace(' dependable.', ' <em>dependable.</em>')}</h1><p class="lede">Thoughtfully engineered solar and electrical solutions for homes, businesses and everything between.</p><div class="actions"><a class="button primary" href="#solar">Explore our work <span>${icon('arrow')}</span></a><a class="text-link" href="#contact">Talk to an expert <span>${icon('arrow')}</span></a></div></div><div class="hero-note"><span class="tiny-sun">☀</span><div><b>Powering brighter choices</b><small>Across residential & commercial spaces</small></div></div><div class="scroll">Scroll to explore <span>↓</span></div></section>
<section class="intro" id="about"><div class="section-label">01 / WHO WE ARE</div><div><h2>One trusted partner.<br/><em>Two essential worlds.</em></h2><p>We bring together clean solar energy and reliable electrical expertise under one roof — so every space can be brighter, smarter, and built to last.</p><a href="#contact" class="text-link dark">Discover our story <span>${icon('arrow')}</span></a></div></section>
<section class="worlds"><a class="world solar" id="solar" href="#contact" style="background-image:linear-gradient(0deg,rgba(3,37,28,.78),rgba(3,37,28,.08)),url('${content.solarImage}')"><div class="world-number">01</div><div><span class="world-icon">${icon('sun')}</span><h3>Solar<br/>Solutions</h3><p>Make the most of every ray.</p></div><span class="round-arrow">${icon('arrow')}</span></a><a class="world electrical" id="electrical" href="#contact" style="background-image:linear-gradient(0deg,rgba(17,23,30,.84),rgba(17,23,30,.12)),url('${content.electricImage}')"><div class="world-number">02</div><div><span class="world-icon bolt">${icon('bolt')}</span><h3>Electrical<br/>Essentials</h3><p>Power that simply performs.</p></div><span class="round-arrow">${icon('arrow')}</span></a></section>
<section class="promise"><p class="eyebrow">THE SOLARA & VOLT PROMISE</p><h2>Good energy starts<br/>with <em>good people.</em></h2><div class="promise-grid"><div><b>01</b><h4>Built around you</h4><p>No cookie-cutter installations. We listen, assess and design for your space.</p></div><div><b>02</b><h4>Quality without shortcuts</h4><p>Trusted materials, skilled hands and work we are proud to stand behind.</p></div><div><b>03</b><h4>Here for the long run</h4><p>Clear advice and dependable support, long after installation day.</p></div></div></section>
<section class="contact" id="contact"><div><p class="eyebrow">LET'S START A CONVERSATION</p><h2>Your next bright<br/>idea starts <em>here.</em></h2></div><div class="contact-card"><p>Whether you’re ready to begin or just considering what’s possible, we’d love to hear from you.</p><a class="button light" href="mailto:${content.email}">Get in touch <span>${icon('arrow')}</span></a><div class="contact-details"><a href="tel:${content.phone.replace(/\s/g,'')}">${content.phone}</a><a href="mailto:${content.email}">${content.email}</a></div></div></section></main>`}
function footer(){return `<footer><a class="brand" href="#home"><span class="mark">S</span><span>${content.businessName}</span></a><span>© ${new Date().getFullYear()} ${content.businessName}. Made for a brighter tomorrow.</span><button class="admin-link">Manage site</button></footer>`}
function render(){app.innerHTML = nav()+home()+footer(); bind();}
function bind(){document.querySelector('.admin-link').onclick=()=>location.href='./admin/'; document.querySelector('.mobile-menu').onclick=()=>document.querySelector('.nav nav').classList.toggle('show');}
function openAdmin(){ const modal=document.createElement('div'); modal.className='modal'; modal.innerHTML=`<div class="admin-panel"><button class="close">${icon('close')}</button><p class="eyebrow">CONTENT STUDIO</p><h2>Keep your site current.</h2><p class="admin-copy">Updates are stored in this browser for this demo. Connect the same interface to a free CMS such as Decap CMS or Sanity when publishing.</p><form><label>Business name<input name="businessName" value="${content.businessName}"></label><label>Headline<input name="tagline" value="${content.tagline}"></label><label>Phone<input name="phone" value="${content.phone}"></label><label>Email<input name="email" value="${content.email}"></label><label>Hero image URL<input name="heroImage" value="${content.heroImage}"></label><label>Solar image URL<input name="solarImage" value="${content.solarImage}"></label><label>Electrical image URL<input name="electricImage" value="${content.electricImage}"></label><div class="file-row"><label>Or upload a hero image<input class="file" type="file" accept="image/*"></label><span>Best: 1800 × 1100px</span></div><button class="button primary" type="submit">Save changes <span>${icon('arrow')}</span></button></form></div>`; document.body.append(modal); modal.querySelector('.close').onclick=()=>modal.remove(); modal.onclick=e=>{if(e.target===modal) modal.remove()}; modal.querySelector('.file').onchange=e=>{const f=e.target.files[0];if(!f)return;const reader=new FileReader();reader.onload=()=>modal.querySelector('[name=heroImage]').value=reader.result;reader.readAsDataURL(f)};modal.querySelector('form').onsubmit=e=>{e.preventDefault(); Object.assign(content,Object.fromEntries(new FormData(e.target))); save();modal.remove();render()};}
render();
fetch('./content/site.json').then(r=>r.ok?r.json():null).then(data=>{if(data){Object.assign(content,data);render()}}).catch(()=>{});
